{% set version = "2.11.0.dev" %}
{% set build = 1 %}

# mpi must be defined for conda-smithy lint
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'nompi' %}
# prefer nompi builds via a build number offset
{% set build = build + 100 %}
{% endif %}

{% set commit = "f525d1c180f6b4bc59726faf833fd50a26d57d83" %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ commit }}.tar.gz
  sha256: b199608bfff08257ab2bff03d6ab0546161359f72a3670b3ad8ef73a63c3b3a2
  patches:
    - FIX__init_`self_mpi`_as_None_in_`setup_configure_py`.patch

build:
  number: {{ build }}
  skip: True  # [py2k]
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `pkg * mpi_mpich_*` for mpich
  # `hdf5 * mpi_*` for any mpi
  # `hdf5 * nompi_*` for no mpi
  string: "{{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - numpy
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    - hdf5
    - hdf5 * {{ mpi_prefix }}_*
    - cython >=0.25
    - pkgconfig
    - cached-property
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ mpi }}  # [mpi != 'nompi']
    - mpi4py  # [mpi != 'nompi']
    - hdf5
    - pyreadline  # [win]
    - cached-property

test:
  requires:
    - pytest
  imports:
    - h5py
  commands:
    - pytest -rxXs -k "not (test_mpio or test_mpi_atomic or test_close_multiple_mpio_driver)" --pyargs h5py

about:
  home: http://www.h5py.org/
  license: BSD-3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
    - tacaswell
    - ocefpaf
    - minrk
