{% set version = "2.8.0" %}
{% set sha256 = "eae41382be28b7264824450ce343dd625f972bedaaa3b0cced284986aabcbaee" %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}

  host:
    - python
    - setuptools
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - hdf5 1.10.1
    - cython
    - six
    - pkgconfig

  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    # when this is changed also update bld.bat
    - hdf5 1.10.1
    - six
    - unittest2    # [py26 or py27]
    - pyreadline  # [win]

test:
  imports:
    - h5py

about:
  home: http://www.h5py.org/
  license: BSD 3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
    - tacaswell
    - carlodri
