{% set version = "2.8.0" %}

package:
  name: h5py
  version: {{ version }}

source:
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  sha256: eae41382be28b7264824450ce343dd625f972bedaaa3b0cced284986aabcbaee

build:
  number: 1003

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - pip
    - numpy
    - hdf5 1.10.2
    - cython
    - six
    - pkgconfig
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5 1.10.2
    - six
    - unittest2  # [py26 or py27]
    - pyreadline  # [win]

test:
  imports:
    - h5py

about:
  home: http://www.h5py.org/
  license: BSD 3-Clause
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pitrou
    - tacaswell
