{% set version = "2.6.0" %}

package:
  name: h5py
  version: {{ version }}

source:
  fn: h5py-{{ version }}.tar.gz
  url: https://github.com/h5py/h5py/archive/{{ version }}.tar.gz
  md5: 613c5776192eaf02ff96a82dfc6d2e78
  patches:
    # Patch a test that appears to be failing in some cases.
    # This patch has been submitted to upstream.
    # See the linked PR for more information.
    #
    # https://github.com/h5py/h5py/pull/697
    #
    - h5py_tests_old_test_file.py.patch
    - h5py_win_setup_build.py.patch

build:
  number: 4

requirements:
  build:
    - python
    - numpy x.x
    - hdf5 1.8.17
    - cython
    - six
    - pkgconfig

  run:
    - python
    - numpy x.x
    - hdf5 1.8.17
    - six
    - unittest2    # [py26]

test:
  imports:
    - h5py

about:
  home: http://www.h5py.org/
  license: BSD 3-Clause
  summary: Read and write HDF5 files from Python.

extra:
  recipe-maintainers:
    - jakirkham
