build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
  win: azure
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
